var Announcement = require('../api/suggestion/suggestion.model');
Announcement.find({}).remove(function() {
    Announcement.create(
          {title: 'Test Title won', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad fugit, accusantium, dolor provident facere, harum magnam molestiae illum impedit ipsa corporis dicta maiores delectus repellat recusandae architecto inventore qui fuga.',
	likes: 10,
	date: new Date(),
	tags: ['one string', 'two string', 'red string', 'blue string'],
	geometry: {coordinates:[10,10]},
	status: 'Super Green'},
	{title: 'Test Title too', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad fugit, accusantium, dolor provident facere, harum magnam molestiae illum impedit ipsa corporis dicta maiores delectus repellat recusandae architecto inventore qui fuga.',
	likes: 10,
	date: new Date(),
	tags: ['one string', 'two string', 'red string', 'blue string'],
	geometry: {coordinates:[10,10]},
	status: 'Super Green'},
	{title: 'Test Title tree', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad fugit, accusantium, dolor provident facere, harum magnam molestiae illum impedit ipsa corporis dicta maiores delectus repellat recusandae architecto inventore qui fuga.',
	likes: 10,
	date: new Date(),
	tags: ['one string', 'two string', 'red string', 'blue string'],
	geometry: {coordinates:[10,10]},
	status: 'Super Green'},
	{title: 'Test Title fore', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad fugit, accusantium, dolor provident facere, harum magnam molestiae illum impedit ipsa corporis dicta maiores delectus repellat recusandae architecto inventore qui fuga.',
	likes: 10,
	date: new Date(),
	tags: ['one string', 'two string', 'red string', 'blue string'],
	geometry: {coordinates:[10,10]},
	status: 'Super Green'},
	{title: 'Test Title live', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad fugit, accusantium, dolor provident facere, harum magnam molestiae illum impedit ipsa corporis dicta maiores delectus repellat recusandae architecto inventore qui fuga.',
	likes: 10,
	date: new Date(),
	tags: ['one string', 'two string', 'red string', 'blue string'],
	geometry: {coordinates:[10,10]},
	status: 'Super Green'});
});
